<?php
/**
 * Created by PhpStorm.
 * User: Peter
 * Date: 06.06.2018
 * Time: 11:16
 */

namespace App\Http\Middleware;

use Closure;
use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Foundation\Http\Middleware\TrimStrings as Middleware;



class SuperAdminLogin extends Middleware
{
    public function handle($request, Closure $next, ...$attributes)
    {
        if ($request->isMethod('post')) {
            $this->authenticate($request);
        }

        if (!Auth::check()) {
            return response()->view('vendor.adminlte.login');
        }

        if(Auth::user()->name != 'Admin') {
            Auth::logout();
            return response()->view('vendor.adminlte.login');
        }
        return parent::handle($request, $next, $attributes); // TODO: Change the autogenerated stub
    }


    public function authenticate($request)
    {
        if ($request->email == env('ADMIN_EMAIL') && $request->password == env('ADMIN_PASS')) {

            $user = new User;
            $user->name = 'Admin';
            $user->email = $request->email;
            $user->password = $request->password;
            Auth::login($user, true);

            return redirect()->route('customers.index');
        } else {
            return redirect()->back()
                ->withErrors([
                    'Дані авторизації не правильні',
                ]);
        }
    }
}